server.max-http-request-header-size=655360000
server.port=8084
server.servlet.context-path=/

openapi.service.title=kishada-voting-service doc
openapi.service.version=1.0.0
openapi.service.url=http://localhost:24401

springdoc.api-docs.path=/kishada-voting-service/v3/api-docs
springdoc.swagger-ui.path=/kishada-voting-service/swagger-ui.html

storage.directory.path=${UPLOAD_PATH:/data/uploads/voting/}

introspector.uri=${INTROSPECTOR_URL}

user-info-uri=${USER_INFO_URL}

user.service.url=${USER_SERVICE_URL}

uaa.client-id=${UAA_CLIENT:uaa-client}
uaa.client-secret=${UAA_CLIENT_SECRET:12345678}

spring.application.name=kishada-voting-service
spring.data.redis.host=localhost
spring.data.redis.password=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
spring.data.redis.port=6379

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=${DB_PASS}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}

spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=update

eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=1
eureka.instance.lease-expiration-duration-in-seconds=2
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone=${EUREKA_DEFAULT_ZONE:http://127.0.0.1:24400/eureka/}

logging.level.org.springframework.security.oauth2=trace
